FileName <- 'household_power_consumption.txt'
df <- read.table(FileName, sep = ';', header = TRUE, quote = "", na.strings = "?", stringsAsFactors = FALSE)
df[,1] <- as.Date(df[,1], format = "%d/%m/%Y")
DTTmp <- paste(df[,1],df[,2])
df$DateTime <- strptime(DTTmp, "%Y-%m-%d %H:%M:%S")
dfuse <- subset(df, df$Date >= as.Date("2007-02-01") & df$Date <= as.Date("2007-02-02"))

png(file = "plot4.png", width = 480, height = 480, units = "px")
par(mfrow = c(2,2))
plot(dfuse$DateTime, dfuse$Global_active_power, xlab = "", ylab = "Global Active Power (kilowatts)", type = "l")
plot(dfuse$DateTime, dfuse$Voltage, xlab = "datetime", ylab = "Voltage", type = "l")
plot(dfuse$DateTime, dfuse$Sub_metering_1, ylim = c(0, max(dfuse$Sub_metering_1)), xlab = "", ylab = "Energy sub metering", type = "l")
par(new = TRUE)
plot(dfuse$DateTime, dfuse$Sub_metering_2, ylim = c(0, max(dfuse$Sub_metering_1)), xlab = "", ylab = "Energy sub metering", type = "l", col = "red")
par(new = TRUE)
plot(dfuse$DateTime, dfuse$Sub_metering_3, ylim = c(0, max(dfuse$Sub_metering_1)), xlab = "", ylab = "Energy sub metering", type = "l", col = "blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c('black','red','blue'), bty = "n", lty=1,lwd=1.5)
plot(dfuse$DateTime, dfuse$Global_reactive_power, xlab = "datetime", ylab = "Global_reactive_power", type = "l")
dev.off()